// <auto-generated />
using System;
using GossipGastropodsBackEnd.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GossipGastropodsBackEnd.Migrations
{
    [DbContext(typeof(GossipContext))]
    [Migration("20190609194726_AddLikesTable")]
    partial class AddLikesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PostId");

                    b.Property<byte>("PostType");

                    b.Property<Guid>("UserGuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserGuid");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.User", b =>
                {
                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<bool>("EmailVerified");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("ProfilePicture");

                    b.HasKey("GUID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Models.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsEdited");

                    b.Property<string>("PostType")
                        .IsRequired();

                    b.Property<Guid>("UserGuid");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator<string>("PostType").HasValue("PostBase");
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Comment", b =>
                {
                    b.HasBaseType("GossipGastropodsBackEnd.Models.PostBase");

                    b.Property<int>("PostId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserGuid");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Post", b =>
                {
                    b.HasBaseType("GossipGastropodsBackEnd.Models.PostBase");

                    b.Property<string>("FilePaths");

                    b.HasIndex("UserGuid")
                        .HasName("IX_PostBase_UserGuid1");

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Like", b =>
                {
                    b.HasOne("GossipGastropodsBackEnd.Models.PostBase", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GossipGastropodsBackEnd.Entities.User", "Owner")
                        .WithMany("Likes")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Comment", b =>
                {
                    b.HasOne("GossipGastropodsBackEnd.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GossipGastropodsBackEnd.Entities.User", "Owner")
                        .WithMany("Comments")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GossipGastropodsBackEnd.Entities.Post", b =>
                {
                    b.HasOne("GossipGastropodsBackEnd.Entities.User", "Owner")
                        .WithMany("Posts")
                        .HasForeignKey("UserGuid")
                        .HasConstraintName("FK_PostBase_Users_UserGuid1")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
